/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio4.interfaces;

import ejercicio4.simulacion.Distribucion;
import ejercicio4.simulacion.Simulacion;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Agustina
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();

        // esto esta igual que en el check
        habilitarCampos(false);
        
        tbl_distribuciones.setModel(Distribucion.getDistribucionPredeterminada());

        lbl_error.setForeground(Interfaz.COLOR_ROJO);
        lbl_error.setVisible(false);
//        habilitarCampos(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_distribuciones = new javax.swing.JTable();
        btn_guardarDistribucion = new javax.swing.JButton();
        chb_distribucionPorDefecto = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_minReservacionesPermitidas = new javax.swing.JTextField();
        txt_maxReservacionesPermitidas = new javax.swing.JTextField();
        btn_guardarDatosDistribucion = new javax.swing.JButton();
        lbl_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio 4");
        setResizable(false);

        tbl_distribuciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pasajeros", "Prob."
            }
        ));
        jScrollPane1.setViewportView(tbl_distribuciones);

        btn_guardarDistribucion.setText("Guardar distribución");
        btn_guardarDistribucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarDistribucionActionPerformed(evt);
            }
        });

        chb_distribucionPorDefecto.setSelected(true);
        chb_distribucionPorDefecto.setText("Usar estrategia por defecto");
        chb_distribucionPorDefecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chb_distribucionPorDefectoMouseClicked(evt);
            }
        });
        chb_distribucionPorDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chb_distribucionPorDefectoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la distribución", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Cantidad míx. pasajeros que se presentan:");

        jLabel2.setText("Cantidad máx. de reservaciones permitidas:");

        btn_guardarDatosDistribucion.setText("Guardar datos");
        btn_guardarDatosDistribucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarDatosDistribucionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)
                                .addComponent(txt_minReservacionesPermitidas, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(txt_maxReservacionesPermitidas)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btn_guardarDatosDistribucion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_minReservacionesPermitidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_maxReservacionesPermitidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_guardarDatosDistribucion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_error.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_error.setText("Campos inválidos y/o faltantes.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btn_guardarDistribucion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chb_distribucionPorDefecto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chb_distribucionPorDefecto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_guardarDistribucion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_error)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chb_distribucionPorDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chb_distribucionPorDefectoActionPerformed
        lbl_error.setVisible(false);
        DefaultTableModel modelo;
        if (chb_distribucionPorDefecto.isSelected()) {
            habilitarCampos(false);
            modelo = Distribucion.getDistribucionPredeterminada();
            modelo.setColumnCount(2);
            tbl_distribuciones.setModel(modelo);
            return;
        }
        habilitarCampos(true);
        String[] cabecera = {"Pasajeros", "Prob."};
        modelo = new DefaultTableModel(cabecera, 0);
        tbl_distribuciones.setModel(modelo);
    }//GEN-LAST:event_chb_distribucionPorDefectoActionPerformed

    private void chb_distribucionPorDefectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chb_distribucionPorDefectoMouseClicked

    }//GEN-LAST:event_chb_distribucionPorDefectoMouseClicked

    private void btn_guardarDatosDistribucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarDatosDistribucionActionPerformed
        // validaciones de los campos
        lbl_error.setVisible(false);
        boolean todoOK = true;

        int maxReservacionesPermitidas = validarCampoNumericoTxt(txt_maxReservacionesPermitidas);
        if (maxReservacionesPermitidas == -1 || maxReservacionesPermitidas <= 0) {
            todoOK = false;
        }
        int minReservacionesPermitidas = validarCampoNumericoTxt(txt_minReservacionesPermitidas);
        if (minReservacionesPermitidas == -1 || minReservacionesPermitidas <= 0) {
            todoOK = false;
        }
        if (minReservacionesPermitidas > maxReservacionesPermitidas) {
            todoOK = false;
        }
        if (!todoOK) {
            lbl_error.setVisible(true);
            return;
        }

        // habilitaciones/deshabilitaciones de campos
        txt_maxReservacionesPermitidas.setEnabled(false);
        txt_minReservacionesPermitidas.setEnabled(false);
        btn_guardarDatosDistribucion.setEnabled(false);
        btn_guardarDistribucion.setEnabled(true);

        // aca se crea el modelo de la tabla para la carga de distribuciones
        String[] cabecera = {"Pasajeros", "Prob."};
        int rows = maxReservacionesPermitidas - minReservacionesPermitidas + 1;
        DefaultTableModel modelo = new DefaultTableModel(cabecera, rows);
        int aux = minReservacionesPermitidas;
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.setValueAt(aux++, i, 0);
            modelo.setValueAt(0.0, i, 1);
        }
        tbl_distribuciones.setModel(modelo);
    }//GEN-LAST:event_btn_guardarDatosDistribucionActionPerformed

    private void btn_guardarDistribucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarDistribucionActionPerformed
        lbl_error.setVisible(false);
        // verificar que la suma de todas las probabilidades sea igual a 1
        if (Distribucion.verificarModelo((DefaultTableModel) tbl_distribuciones.getModel())) {
            // se crea la distribucion, cargándola en la Simulacion
            DefaultTableModel modelo = (DefaultTableModel) tbl_distribuciones.getModel();
            Simulacion.cargarModeloDistribucion(modelo);
            
            // aca va a la ventana de la simulación
            Principal ventana = new Principal();
            ventana.setLocationRelativeTo(null);
            ventana.setVisible(true);
            return;
        }
        // avisa que los datos no son válidos
        lbl_error.setVisible(true);
    }//GEN-LAST:event_btn_guardarDistribucionActionPerformed

    private int validarCampoNumericoTxt(javax.swing.JTextField txt) {
        int n = -1;
        try {
            n = Integer.parseInt(txt.getText());
        } catch (NumberFormatException e) {
            return n;
        }
        return n;
    }

    private void habilitarCampos(boolean flag) {
        // carga de valores por defecto
        txt_maxReservacionesPermitidas.setText("64");
        txt_minReservacionesPermitidas.setText("58");

        // habilitar/deshabilitar campos
        txt_maxReservacionesPermitidas.setEnabled(flag);
        txt_minReservacionesPermitidas.setEnabled(flag);
        btn_guardarDatosDistribucion.setEnabled(flag);
        tbl_distribuciones.setEnabled(flag);
        btn_guardarDistribucion.setEnabled(!flag);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardarDatosDistribucion;
    private javax.swing.JButton btn_guardarDistribucion;
    private javax.swing.JCheckBox chb_distribucionPorDefecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JTable tbl_distribuciones;
    private javax.swing.JTextField txt_maxReservacionesPermitidas;
    private javax.swing.JTextField txt_minReservacionesPermitidas;
    // End of variables declaration//GEN-END:variables
}
