/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejercicio4.interfaces;

import ejercicio4.simulacion.Simulacion;

/**
 *
 * @author Agustina
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();     
        
        tbl_distribuciones.setModel(Simulacion.getDistribucion().getModeloDistribucion());
                
        // seteo inicial de los campos de la ventana
        lbl_reservacionesSimulacion.setText("" + Simulacion.getDistribucion().getMaxPasajerosPresentes());
        tbl_distribuciones.setEnabled(false);
        lbl_utilidadActual.setText("" + Simulacion.UTILIDAD_PROMEDIO_ACTUAL);
        lbl_error.setForeground(Interfaz.COLOR_ROJO);
        lbl_error.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_reservacionesAceptadas = new javax.swing.ButtonGroup();
        panel_situacionActual = new javax.swing.JPanel();
        lbl_reservacionesActual = new javax.swing.JLabel();
        lbl_utilidadActual = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        panel_resultadoSimulacion = new javax.swing.JPanel();
        lbl_reservacionesSimulacion = new javax.swing.JLabel();
        lbl_utilidadSimulacion = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_vuelosSimulados = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_simulacion = new javax.swing.JTable();
        panel_simulacion = new javax.swing.JPanel();
        panel_reservacionesAceptadas = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_distribuciones = new javax.swing.JTable();
        panel_rango = new javax.swing.JPanel();
        txt_desde = new javax.swing.JTextField();
        txt_hasta = new javax.swing.JTextField();
        lbl_hasta = new javax.swing.JLabel();
        txt_nroExperimentos = new javax.swing.JTextField();
        btn_simular = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lbl_error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ejercicio 4");
        setMinimumSize(new java.awt.Dimension(756, 512));
        setSize(new java.awt.Dimension(756, 512));

        panel_situacionActual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Situación actual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbl_reservacionesActual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_reservacionesActual.setText("60");
        lbl_reservacionesActual.setToolTipText("");

        lbl_utilidadActual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_utilidadActual.setText("VALOR");

        jLabel4.setText("Reservaciones permitidas:");

        jLabel5.setText("Utilidad promedio por vuelo: $");

        javax.swing.GroupLayout panel_situacionActualLayout = new javax.swing.GroupLayout(panel_situacionActual);
        panel_situacionActual.setLayout(panel_situacionActualLayout);
        panel_situacionActualLayout.setHorizontalGroup(
            panel_situacionActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_situacionActualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_situacionActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_situacionActualLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_reservacionesActual))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_situacionActualLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_utilidadActual)))
                .addContainerGap())
        );
        panel_situacionActualLayout.setVerticalGroup(
            panel_situacionActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_situacionActualLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_situacionActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_reservacionesActual)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_situacionActualLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_utilidadActual)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_resultadoSimulacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultado de la simulación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lbl_reservacionesSimulacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_reservacionesSimulacion.setText("VALOR");

        lbl_utilidadSimulacion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_utilidadSimulacion.setText("-");

        jLabel2.setText("Reservaciones permitidas:");

        jLabel3.setText("Utilidad promedio por vuelo: $");

        jLabel1.setText("Cant. de vuelos simulados:");

        lbl_vuelosSimulados.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_vuelosSimulados.setText("-");

        javax.swing.GroupLayout panel_resultadoSimulacionLayout = new javax.swing.GroupLayout(panel_resultadoSimulacion);
        panel_resultadoSimulacion.setLayout(panel_resultadoSimulacionLayout);
        panel_resultadoSimulacionLayout.setHorizontalGroup(
            panel_resultadoSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_resultadoSimulacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_resultadoSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_resultadoSimulacionLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_utilidadSimulacion))
                    .addGroup(panel_resultadoSimulacionLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_reservacionesSimulacion))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_resultadoSimulacionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_vuelosSimulados))
                    .addComponent(jSeparator1))
                .addContainerGap())
        );
        panel_resultadoSimulacionLayout.setVerticalGroup(
            panel_resultadoSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_resultadoSimulacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_resultadoSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_reservacionesSimulacion)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_resultadoSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_utilidadSimulacion)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_resultadoSimulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lbl_vuelosSimulados))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tbl_simulacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_simulacion.setEnabled(false);
        tbl_simulacion.setSelectionBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tbl_simulacion);

        panel_simulacion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Simulación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        panel_reservacionesAceptadas.setBorder(javax.swing.BorderFactory.createTitledBorder("Pasajeros que se presentan"));

        tbl_distribuciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_distribuciones.setEnabled(false);
        jScrollPane2.setViewportView(tbl_distribuciones);

        javax.swing.GroupLayout panel_reservacionesAceptadasLayout = new javax.swing.GroupLayout(panel_reservacionesAceptadas);
        panel_reservacionesAceptadas.setLayout(panel_reservacionesAceptadasLayout);
        panel_reservacionesAceptadasLayout.setHorizontalGroup(
            panel_reservacionesAceptadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reservacionesAceptadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_reservacionesAceptadasLayout.setVerticalGroup(
            panel_reservacionesAceptadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_reservacionesAceptadasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel_rango.setBorder(javax.swing.BorderFactory.createTitledBorder("Rango a mostrar"));

        txt_desde.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_desde.setText("1");
        txt_desde.setToolTipText("Número de experimento desde el cual se quiere mostrar en tabla");

        txt_hasta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_hasta.setText("30");
        txt_hasta.setToolTipText("Número de experimento hasta el cual se quiere mostrar en tabla");

        lbl_hasta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_hasta.setText(" - ");

        javax.swing.GroupLayout panel_rangoLayout = new javax.swing.GroupLayout(panel_rango);
        panel_rango.setLayout(panel_rangoLayout);
        panel_rangoLayout.setHorizontalGroup(
            panel_rangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rangoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_desde, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_hasta)
                .addContainerGap())
        );
        panel_rangoLayout.setVerticalGroup(
            panel_rangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_rangoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_rangoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_desde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_hasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_hasta))
                .addContainerGap())
        );

        txt_nroExperimentos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nroExperimentos.setText("100");
        txt_nroExperimentos.setToolTipText("Número de experimentos a simular");
        txt_nroExperimentos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nroExperimentosKeyTyped(evt);
            }
        });

        btn_simular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_simular.setText("SIMULAR");
        btn_simular.setToolTipText("Generar simulación con los datos cargados");
        btn_simular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simularActionPerformed(evt);
            }
        });

        jLabel6.setText("Cantidad de vuelos");

        javax.swing.GroupLayout panel_simulacionLayout = new javax.swing.GroupLayout(panel_simulacion);
        panel_simulacion.setLayout(panel_simulacionLayout);
        panel_simulacionLayout.setHorizontalGroup(
            panel_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_simulacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_reservacionesAceptadas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_rango, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_simulacionLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_nroExperimentos))
                    .addComponent(btn_simular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel_simulacionLayout.setVerticalGroup(
            panel_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_simulacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_reservacionesAceptadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_simulacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nroExperimentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_rango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_simular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_error.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbl_error.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_error.setText("Campos inválidos y/o faltantes.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_simulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_error, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_situacionActual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_resultadoSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_simulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(panel_situacionActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(panel_resultadoSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_error)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simularActionPerformed
        lbl_error.setVisible(false);
        boolean todoOK = true;

        // validaciones de los campos
        int exp = Interfaz.validarCampoNumericoTxt(txt_nroExperimentos);
        if (exp == -1 || exp == 0) {
            todoOK = false;
        }
        int desde = Interfaz.validarCampoNumericoTxt(txt_desde);
        if (desde == -1) {
            todoOK = false;
        }
        int hasta = Interfaz.validarCampoNumericoTxt(txt_hasta);
        if (hasta == -1) {
            todoOK = false;
        }
        if (hasta > exp || desde > hasta || desde <= 0) {
            todoOK = false;
        }
        if (!todoOK) {
            lbl_error.setVisible(true);
            return;
        }
        
        // aca va la parte que hacemos la simulación propiamente dicha        
        tbl_simulacion.setModel(Simulacion.generar(exp, desde, hasta));

        // mostrar los resultados de la simulación
        lbl_vuelosSimulados.setText(txt_nroExperimentos.getText());
        long utilidadPromedioSimulacion = Simulacion.getUtilidadPromedio();
        lbl_utilidadSimulacion.setText("" + utilidadPromedioSimulacion);
        if (utilidadPromedioSimulacion > Simulacion.UTILIDAD_PROMEDIO_ACTUAL) {
            lbl_reservacionesSimulacion.setForeground(Interfaz.COLOR_VERDE);
            lbl_utilidadSimulacion.setForeground(Interfaz.COLOR_VERDE);
        } else {
            lbl_reservacionesSimulacion.setForeground(Interfaz.COLOR_ROJO);
            lbl_utilidadSimulacion.setForeground(Interfaz.COLOR_ROJO);
        }
    }//GEN-LAST:event_btn_simularActionPerformed
    
    private void txt_nroExperimentosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nroExperimentosKeyTyped

    }//GEN-LAST:event_txt_nroExperimentosKeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg_reservacionesAceptadas;
    private javax.swing.JButton btn_simular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_error;
    private javax.swing.JLabel lbl_hasta;
    private javax.swing.JLabel lbl_reservacionesActual;
    private javax.swing.JLabel lbl_reservacionesSimulacion;
    private javax.swing.JLabel lbl_utilidadActual;
    private javax.swing.JLabel lbl_utilidadSimulacion;
    private javax.swing.JLabel lbl_vuelosSimulados;
    private javax.swing.JPanel panel_rango;
    private javax.swing.JPanel panel_reservacionesAceptadas;
    private javax.swing.JPanel panel_resultadoSimulacion;
    private javax.swing.JPanel panel_simulacion;
    private javax.swing.JPanel panel_situacionActual;
    private javax.swing.JTable tbl_distribuciones;
    private javax.swing.JTable tbl_simulacion;
    private javax.swing.JTextField txt_desde;
    private javax.swing.JTextField txt_hasta;
    private javax.swing.JTextField txt_nroExperimentos;
    // End of variables declaration//GEN-END:variables
}
